---
title: "Data Manipulation"
output: html_document
---

This file is for doing data manipulation.
```{r message=FALSE}
library(tidyverse)
```

load the litters and pups datasets.

```{r}
litters_df = 
  read_csv(
    file  = "data/FAS_litters.csv",
    skip = 0,
    na = c("","NA",".")
    )

litters_df = janitor::clean_names(litters_df)
litters_df
pups_df = 
  read_csv(
    file  = "data/FAS_pups.csv", skip = 3,
    na = c("","NA",".")
    )
pups_df = janitor::clean_names(pups_df)
pups_df 

```



##select variables

```{r}
select(litters_df, group, litter_number)
select(litters_df, group: gd_of_birth)
select(litters_df, -group)
select(litters_df, starts_with("gd"))
select(litters_df, starts_with("gd"), group)
select(litters_df, GROUP = group, everything())
select(litters_df, -starts_with("gd"))
```

some alternatives

```{r}
rename(litters_df, GROUP = group)
relocate(litters_df, litter_number, gd0_weight)
```

in pups data

```{r}
select(pups_df, litter_number:pd_ears)

```


##"filter" some rows

```{r}
filter(litters_df, gd_of_birth == 19)
filter(litters_df, pups_born_alive <= 5)
filter(litters_df, pups_born_alive != 6)
filter(litters_df, group %in% c("Con7", "Con8"))
filter(litters_df, group %in% c("Con7", "Con8"), pups_born_alive < 7)

drop_na(litters_df, gd0_weight)

```

In pups project, keep only rows where PD walk is less than 1 and sex is 2

```{r}
filter(pups_df,pd_walk < 11, sex == 2)
```


##"mutate" to change some columns

lets add and change some columns.

```{r}
mutate(litters_df,
       wt_gain = gd18_weight - gd0_weight,
       wt_gain_squared = wt_gain**2,
       group = str_to_lower(group))
```

In the pups dataset
```{r}
mutate(pups_df,
       pd_walk_minus_7 = pd_walk - 7)
       
```

##"arrange" the data
```{r}
arrange(litters_df, pups_born_alive)
arrange(litters_df, desc(pups_born_alive))

```

